apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httprouteenforcehostnamesparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.allowedHostnames
        name: Hostnames
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                allowedHostnames:
                  description: "allowedHostnames defines a set of hostnames that are allowed
                    to be used in the HTTPRoute manifest."
                  minItems: 1
                  type: array
                  items:
                    description: "Hostname is the fully qualified domain name of a network
                        host. This matches the RFC 1123 definition of a hostname with
                        2 notable exceptions: \n 1. IPs are not allowed. 2. A hostname
                        may be prefixed with a wildcard label (`*.`). The wildcard label
                        must appear by itself as the first label. \n Hostname can be \"precise\"
                        which is a domain name without the terminating dot of a network
                        host (e.g. \"foo.example.com\") or \"wildcard\", which is a domain
                        name prefixed with a single wildcard label (e.g. `*.example.com`).
                        \n Note that as per RFC1035 and RFC1123, a *label* must consist
                        of lower case alphanumeric characters or '-', and must start and
                        end with an alphanumeric character. No other punctuation is allowed."
                    maxLength: 253
                    minLength: 1
                    pattern: ^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
              required:
                - allowedHostnames
  scope: Namespaced
  names:
    plural: httprouteenforcehostnamesparams
    singular: httprouteenforcehostnamesparam
    kind: HTTPRouteEnforceHostnamesParam
