---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibservicetypeparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.allowedTypes
        name: Types
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                allowedTypes:
                  description: "allowedTypes defines a set of types that are allowed
                    to be used in the Service manifest."
                  minItems: 1
                  type: array
                  items:
                    description: "type determines how the Service is exposed. Defaults
                        to ClusterIP. Valid options are ExternalName, ClusterIP,
                        NodePort, and LoadBalancer. \"ClusterIP\" allocates a cluster-internal
                        IP address for load-balancing to endpoints. Endpoints are determined
                        by the selector or if that is not specified, by manual construction
                        of an Endpoints object or EndpointSlice objects. If clusterIP is None,
                        no virtual IP is allocated and the endpoints are published as a set of
                        endpoints rather than a virtual IP. \"NodePort\" builds on ClusterIP and
                        allocates a port on every node which routes to the same endpoints as
                        the clusterIP. \"LoadBalancer\" builds on NodePort and creates an external
                        load-balancer (if supported in the current cloud) which routes to the
                        same endpoints as the clusterIP. \"ExternalName\" aliases this service to
                        the specified externalName. Several other fields do not apply to
                        ExternalName services."
                    type: string
                    enum:
                      - "ClusterIP"
                      - "NodePort"
                      - "LoadBalancer"
                      - "ExternalName"
              required:
                - allowedTypes
  scope: Namespaced
  names:
    plural: vaplibservicetypeparams
    singular: vaplibservicetypeparam
    kind: VAPLibServiceTypeParam
