apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibhelmreleaseenforcefieldsparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.targetNamespace
        name: TargetNamespace
        type: string
      - jsonPath: .spec.serviceAccountName
        name: ServiceAccountName
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespace:
                  description: "TargetNamespace to target when performing operations
                    for the HelmRelease. Defaults to the namespace of the HelmRelease."
                  maxLength: 63
                  minLength: 1
                  type: string
                serviceAccountName:
                  description: "The name of the Kubernetes service account to impersonate
                    when reconciling this HelmRelease."
                  type: string
  scope: Namespaced
  names:
    plural: vaplibhelmreleaseenforcefieldsparams
    singular: vaplibhelmreleaseenforcefieldsparam
    kind: VAPLibHelmReleaseEnforceFieldsParam
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibhttprouteenforcehostnamesparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.allowedHostnames
        name: Hostnames
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                allowedHostnames:
                  description: "allowedHostnames defines a set of hostnames that are allowed
                    to be used in the HTTPRoute manifest."
                  minItems: 1
                  type: array
                  items:
                    description: "Hostname is the fully qualified domain name of a network
                        host. This matches the RFC 1123 definition of a hostname with
                        2 notable exceptions: \n 1. IPs are not allowed. 2. A hostname
                        may be prefixed with a wildcard label (`*.`). The wildcard label
                        must appear by itself as the first label. \n Hostname can be \"precise\"
                        which is a domain name without the terminating dot of a network
                        host (e.g. \"foo.example.com\") or \"wildcard\", which is a domain
                        name prefixed with a single wildcard label (e.g. `*.example.com`).
                        \n Note that as per RFC1035 and RFC1123, a *label* must consist
                        of lower case alphanumeric characters or '-', and must start and
                        end with an alphanumeric character. No other punctuation is allowed."
                    maxLength: 253
                    minLength: 1
                    pattern: ^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
              required:
                - allowedHostnames
  scope: Namespaced
  names:
    plural: vaplibhttprouteenforcehostnamesparams
    singular: vaplibhttprouteenforcehostnamesparam
    kind: VAPLibHTTPRouteEnforceHostnamesParam
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibkustomizationenforcefieldsparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.targetNamespace
        name: TargetNamespace
        type: string
      - jsonPath: .spec.serviceAccountName
        name: ServiceAccountName
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespace:
                  description: "TargetNamespace to target when performing operations
                    for the Kustomization. Defaults to the namespace of the Kustomization."
                  maxLength: 63
                  minLength: 1
                  type: string
                serviceAccountName:
                  description: "The name of the Kubernetes service account to impersonate
                    when reconciling this Kustomization."
                  type: string
  scope: Namespaced
  names:
    plural: vaplibkustomizationenforcefieldsparams
    singular: vaplibkustomizationenforcefieldsparam
    kind: VAPLibKustomizationEnforceFieldsParam
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibserviceenforcetypeparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.allowedTypes
        name: Types
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                allowedTypes:
                  description: "allowedTypes defines a set of types that are allowed
                    to be used in the Service manifest."
                  minItems: 1
                  type: array
                  items:
                    description: "type determines how the Service is exposed. Defaults
                        to ClusterIP. Valid options are ExternalName, ClusterIP,
                        NodePort, and LoadBalancer. \"ClusterIP\" allocates a cluster-internal
                        IP address for load-balancing to endpoints. Endpoints are determined
                        by the selector or if that is not specified, by manual construction
                        of an Endpoints object or EndpointSlice objects. If clusterIP is None,
                        no virtual IP is allocated and the endpoints are published as a set of
                        endpoints rather than a virtual IP. \"NodePort\" builds on ClusterIP and
                        allocates a port on every node which routes to the same endpoints as
                        the clusterIP. \"LoadBalancer\" builds on NodePort and creates an external
                        load-balancer (if supported in the current cloud) which routes to the
                        same endpoints as the clusterIP. \"ExternalName\" aliases this service to
                        the specified externalName. Several other fields do not apply to
                        ExternalName services."
                    type: string
                    enum:
                      - "ClusterIP"
                      - "NodePort"
                      - "LoadBalancer"
                      - "ExternalName"
              required:
                - allowedTypes
  scope: Namespaced
  names:
    plural: vaplibserviceenforcetypeparams
    singular: vaplibserviceenforcetypeparam
    kind: VAPLibServiceEnforceTypeParam
---
