apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibhelmreleasefieldsparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.targetNamespace
        name: TargetNamespace
        type: string
      - jsonPath: .spec.serviceAccountName
        name: ServiceAccountName
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespace:
                  description: "TargetNamespace to target when performing operations
                    for the HelmRelease. Defaults to the namespace of the HelmRelease."
                  maxLength: 63
                  minLength: 1
                  type: string
                serviceAccountName:
                  description: "The name of the Kubernetes service account to impersonate
                    when reconciling this HelmRelease."
                  type: string
  scope: Namespaced
  names:
    plural: vaplibhelmreleasefieldsparams
    singular: vaplibhelmreleasefieldsparam
    kind: VAPLibHelmReleaseFieldsParam
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibhttproutefieldsparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.allowedHostnames
        name: Hostnames
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                allowedHostnames:
                  description: "allowedHostnames defines a set of hostnames that are allowed
                    to be used in the HTTPRoute manifest."
                  minItems: 1
                  type: array
                  items:
                    description: "See Hostnames in the official Gateway API HTTPRoute CRD"
                    maxLength: 253
                    minLength: 1
                    pattern: ^(\*\.)?[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                    type: string
                allowedParentRefs:
                  description: "allowedParentRefs defines a set of parent references that
                    are allowed to be used in the HTTPRoute manifests."
                  minItems: 1
                  items:
                    description: "See ParentRefs in the official Gateway API HTTPRoute CRD"
                    properties:
                      group:
                        default: gateway.networking.k8s.io
                        description: "See properties.group in the official Gateway API HTTPRoute CRD"
                        maxLength: 253
                        pattern: ^$|^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                        type: string
                      kind:
                        default: Gateway
                        description: "See properties.kind in the official Gateway API HTTPRoute CRD"
                        maxLength: 63
                        minLength: 1
                        pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                        type: string
                      name:
                        description: "See properties.name in the official Gateway API HTTPRoute CRD"
                        maxLength: 253
                        minLength: 1
                        type: string
                      namespace:
                        description: "See properties.namespace in the official Gateway API HTTPRoute CRD"
                        maxLength: 63
                        minLength: 1
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?$
                        type: string
                      port:
                        description: "See properties.port in the official Gateway API HTTPRoute CRD"
                        format: int32
                        maximum: 65535
                        minimum: 1
                        type: integer
                      sectionName:
                        description: "See properties.sectionName in the official Gateway API HTTPRoute CRD"
                        maxLength: 253
                        minLength: 1
                        pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                        type: string
                    required:
                      - name
                    type: object
                  maxItems: 32
                  type: array
  scope: Namespaced
  names:
    plural: vaplibhttproutefieldsparams
    singular: vaplibhttproutefieldsparam
    kind: VAPLibHTTPRouteFieldsParam
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibkustomizationfieldsparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.targetNamespace
        name: TargetNamespace
        type: string
      - jsonPath: .spec.serviceAccountName
        name: ServiceAccountName
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetNamespace:
                  description: "TargetNamespace to target when performing operations
                    for the Kustomization. Defaults to the namespace of the Kustomization."
                  maxLength: 63
                  minLength: 1
                  type: string
                serviceAccountName:
                  description: "The name of the Kubernetes service account to impersonate
                    when reconciling this Kustomization."
                  type: string
  scope: Namespaced
  names:
    plural: vaplibkustomizationfieldsparams
    singular: vaplibkustomizationfieldsparam
    kind: VAPLibKustomizationFieldsParam
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibservicetypeparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.allowedTypes
        name: Types
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                allowedTypes:
                  description: "allowedTypes defines a set of types that are allowed
                    to be used in the Service manifest."
                  minItems: 1
                  type: array
                  items:
                    description: "type determines how the Service is exposed. Defaults
                        to ClusterIP. Valid options are ExternalName, ClusterIP,
                        NodePort, and LoadBalancer. \"ClusterIP\" allocates a cluster-internal
                        IP address for load-balancing to endpoints. Endpoints are determined
                        by the selector or if that is not specified, by manual construction
                        of an Endpoints object or EndpointSlice objects. If clusterIP is None,
                        no virtual IP is allocated and the endpoints are published as a set of
                        endpoints rather than a virtual IP. \"NodePort\" builds on ClusterIP and
                        allocates a port on every node which routes to the same endpoints as
                        the clusterIP. \"LoadBalancer\" builds on NodePort and creates an external
                        load-balancer (if supported in the current cloud) which routes to the
                        same endpoints as the clusterIP. \"ExternalName\" aliases this service to
                        the specified externalName. Several other fields do not apply to
                        ExternalName services."
                    type: string
                    enum:
                      - "ClusterIP"
                      - "NodePort"
                      - "LoadBalancer"
                      - "ExternalName"
              required:
                - allowedTypes
  scope: Namespaced
  names:
    plural: vaplibservicetypeparams
    singular: vaplibservicetypeparam
    kind: VAPLibServiceTypeParam
---
