---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "grafana-enforce-dashboard-folder.vap-library.com"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["configmaps", "secrets"]
  matchConditions:
    - name: "filter-for-grafana-dashboard-label"
      expression: 'has(object.metadata.labels) && has(object.metadata.labels.grafana_dashboard) && object.metadata.labels.grafana_dashboard == "1"'
  validations:
    - expression: "has(object.metadata.annotations) && has(object.metadata.annotations.grafana_folder) && object.metadata.annotations.grafana_folder == namespaceObject.metadata.name"
      message: "metadata.annotations.grafana_folder must be set to the namespace of the ConfigMap/Secret"
      reason: Invalid
---
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "helmrelease-enforce-fields.vap-library.com"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: vap-library.com/v1beta1
    kind: VAPLibHelmReleaseEnforceFieldsParam
  matchConstraints:
    resourceRules:
    - apiGroups:   ["helm.toolkit.fluxcd.io"]
      apiVersions: ["*"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["helmreleases"]
  validations:
    - expression: >
        !(has(params.spec.targetNamespace)) ||
        (has(object.spec.targetNamespace) && object.spec.targetNamespace == params.spec.targetNamespace)
      messageExpression: "'spec.targetNamespace must be set to ' + string(params.spec.targetNamespace) + '. It is: ' + string(object.spec.targetNamespace)"
      message: "spec.targetNamespace must be set to the namespace specified in the Validating Admission Policy parameter"
      reason: Invalid
    - expression: >
        !(has(params.spec.serviceAccountName)) ||
        (has(object.spec.serviceAccountName) && object.spec.serviceAccountName == params.spec.serviceAccountName)
      messageExpression: "'spec.serviceAccountName must be set to ' + string(params.spec.serviceAccountName) + '. It is: ' + string(object.spec.serviceAccountName)"
      message: "spec.serviceAccountName must be set to the service account specified in the Validating Admission Policy parameter"
      reason: Invalid
---
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "httproute-enforce-hostnames.vap-library.com"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: vap-library.com/v1beta1
    kind: VAPLibHTTPRouteEnforceHostnamesParam
  matchConstraints:
    resourceRules:
    - apiGroups:   ["gateway.networking.k8s.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["httproutes"]
  validations:
    - expression: "has(object.spec.hostnames) && has(params.spec.allowedHostnames) && object.spec.hostnames.all(h, h in params.spec.allowedHostnames)"
      message: "spec.hostnames must be present and each item must be on the spec.allowedHostnames list in the policy parameter"
      reason: Invalid
---
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "kustomization-enforce-fields.vap-library.com"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: vap-library.com/v1beta1
    kind: VAPLibKustomizationEnforceFieldsParam
  matchConstraints:
    resourceRules:
    - apiGroups:   ["kustomize.toolkit.fluxcd.io"]
      apiVersions: ["*"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["kustomizations"]
  validations:
    - expression: >
        !(has(params.spec.targetNamespace)) ||
        (has(object.spec.targetNamespace) && object.spec.targetNamespace == params.spec.targetNamespace)
      messageExpression: "'spec.targetNamespace must be set to ' + string(params.spec.targetNamespace) + '. It is: ' + string(object.spec.targetNamespace)"
      message: "spec.targetNamespace must be set to the namespace specified in the Validating Admission Policy parameter"
      reason: Invalid
    - expression: >
        !(has(params.spec.serviceAccountName)) ||
        (has(object.spec.serviceAccountName) && object.spec.serviceAccountName == params.spec.serviceAccountName)
      messageExpression: "'spec.serviceAccountName must be set to ' + string(params.spec.serviceAccountName) + '. It is: ' + string(object.spec.serviceAccountName)"
      message: "spec.serviceAccountName must be set to the service account specified in the Validating Admission Policy parameter"
      reason: Invalid
---
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "service-enforce-type.vap-library.com"
spec:
  failurePolicy: Fail
  paramKind:
    apiVersion: vap-library.com/v1beta1
    kind: VAPLibServiceEnforceTypeParam
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["services"]
  validations:
    - expression: >
        (!(has(object.spec.type)) && "ClusterIP" in params.spec.allowedTypes) ||
        has(object.spec.type) && object.spec.type in params.spec.allowedTypes
      message: "spec.type must be present and must be on the spec.allowedTypes list or must not be present and 'ClusterIP' must be in the spec.allowedTypes list in the policy parameter"
      reason: Invalid
---
