---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaplibresourcelimittypesparams.vap-library.com
spec:
  group: vap-library.com
  versions:
    - name: v1beta1
      additionalPrinterColumns:
      - jsonPath: .spec.enforcedResourceLimitTypes
        name: Limits
        type: string
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enforcedResourceLimitTypes:
                  description: "enforcedResourceLimitTypes defines a set of resource limit types which
                    must be provided in container manifests."
                  minItems: 1
                  type: array
                  items:
                    description: "resources.limits allows resource limits to be provided on
                        certain resource types. Valid options are cpu, memory,
                        and ephemeral-storage."
                    type: string
                    enum:
                      - "cpu"
                      - "memory"
                      - "ephemeral-storage"
              required:
                - enforcedResourceLimitTypes
  scope: Namespaced
  names:
    plural: vaplibresourcelimittypesparams
    singular: vaplibresourcelimittypesparam
    kind: VAPLibResourceLimitTypesParam
