permissions: write-all
on:
 push:
  tags:
    - 'v*.*.*'

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Package
        run: ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/policies.yaml
            release/bindings.yaml
            release/crds.yaml
      # we want to keep the releases in the git repo too
      - name: Push to git
        uses: EndBug/add-and-commit@v9
        with:
          add: 'release'
          push: main
